server_name: server1

# S3 Object storage config
s3_endpoint: https://<accountid>.r2.cloudflarestorage.com
s3_access_key: <access_key>
s3_secret_access_key: <access_key_secret>
s3_bucket_name: <bucket_name>

# backup config
backup_dirs:
  - /path/to/backup/dir
  
pre_backup_exec:
  - command_1

encrypt_keys:
  - <gpg_key_id_1>
  - <gpg_key_id_2>
  
post_backup_exec:
  - command_1
